///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate SOAPStructStruct
////////////////////////////////////////////////////////////////////////////////////

#include "SOAPStructStruct.h"
#include <axis/common/AxisWrapperAPI.h>

extern int Axis_DeSerialize_SOAPStruct(SOAPStruct* param, IWrapperSoapDeSerializer *pDZ);
extern void* Axis_Create_SOAPStruct(bool bArray = false, int nSize=0);
extern void Axis_Delete_SOAPStruct(SOAPStruct* param, bool bArray = false, int nSize=0);
extern int Axis_Serialize_SOAPStruct(SOAPStruct* param, IWrapperSoapSerializer& pSZ, bool bArray = false);
extern int Axis_GetSize_SOAPStruct();

/////////////////////////////////////////////////////////////////////////////
// This static method serialize a SOAPStructStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_Serialize_SOAPStructStruct(SOAPStructStruct* param, IWrapperSoapSerializer& pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ << "<" << Axis_TypeName_SOAPStructStruct << ">";
	}
	else
	{
		const AxisChar* sPrefix = pSZ.getNewNamespacePrefix();
		pSZ << "<" << Axis_TypeName_SOAPStructStruct << " xsi:type=\"" << sPrefix <<":"
			<< Axis_TypeName_SOAPStructStruct << "\" xmlns:" << sPrefix << "=\""
			<< Axis_URI_SOAPStructStruct << "\">";
	}

	pSZ << pSZ.SerializeBasicType("varString", param->varString, XSD_STRING);
	pSZ << pSZ.SerializeBasicType("varInt", param->varInt, XSD_INT);
	pSZ << pSZ.SerializeBasicType("varFloat", param->varFloat, XSD_FLOAT);
	Axis_Serialize_SOAPStruct(param->varStruct, pSZ);

	pSZ << "</" << Axis_TypeName_SOAPStructStruct << ">";
	return AXIS_SUCCESS;
}

/////////////////////////////////////////////////////////////////////////////
// This static method deserialize a SOAPStructStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_DeSerialize_SOAPStructStruct(SOAPStructStruct* param, IWrapperSoapDeSerializer *pIWSDZ)
{
	param->varString = pIWSDZ->GetString();
	param->varInt = pIWSDZ->GetInt();
	param->varFloat = pIWSDZ->GetFloat();
	param->varStruct = (SOAPStruct*)pIWSDZ->GetObject((void*)Axis_DeSerialize_SOAPStruct
		, (void*)Axis_Create_SOAPStruct, (void*)Axis_Delete_SOAPStruct
		, Axis_TypeName_SOAPStruct, Axis_URI_SOAPStruct);
	return AXIS_SUCCESS;
}
void* Axis_Create_SOAPStructStruct(bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
		return new SOAPStructStruct[nSize];
	else
		return new SOAPStructStruct;
}

/////////////////////////////////////////////////////////////////////////////
// This static method delete a SOAPStructStruct type of object
//////////////////////////////////////////////////////////////////////
void Axis_Delete_SOAPStructStruct(SOAPStructStruct* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/////////////////////////////////////////////////////////////////////////////
// This static method gives the size of SOAPStructStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_GetSize_SOAPStructStruct()
{
	return sizeof(SOAPStructStruct);
}

SOAPStructStruct::SOAPStructStruct()
{
	varStruct = NULL;
}

SOAPStructStruct::~SOAPStructStruct()
{
	delete varStruct;
}

