/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__MATHOPS_CLIENTSTUB_H__INCLUDED_)
#define __MATHOPS_CLIENTSTUB_H__INCLUDED_

#include <axis/client/Stub.h>
/*include Exception header files here*/
#include "DivByZeroStruct.h"
#include "SpecialDetailStruct.h"
#include "OutOfBoundStruct.h"
#include "AxisClientException.h"

/**
  * @class MathOps.h
  * @brief A test class for fault mapping.
  *
  * This class is used to demonstrate fault mapping
  * testing. Here I have generated the stuff using FaultMapping.wsdl. This wsdl
  * simply have several complex types. One such type is DivByZeroStruct which 
  * consists of three simple types(xsd:int,* xsd:foat and xsd:string). 
  * For portType operation "div" we have a fault named
  * DivByZero the message for which is DivByZeroFault which is of the complex
  * type mentioned above(DivByZeroStruct). The server side for this client
  * sample is in $AXISCPP_HOME/tests/server/exceptionTest.
  *
  *
  * @author Damitha Kumarage (damitha@opensource.lk, damitha@jkcsworld.com)
  */

class MathOps :public Stub
{
public:
	MathOps(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP);
	MathOps();
public:
	virtual ~MathOps();
public: 
	int div(int Value0,int Value1);
	int getFaultDetail(char** ppcDetail);
};

#endif /* !defined(__MATHOPS_CLIENTSTUB_H__INCLUDED_)*/
